### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by MimuraKyosuke** [bawaviki/youtube-dl-android#10]
Hello

It cannot be downloaded from YouTube after April 17th.
"START STREAM" also fails.

I was successful in Dailymotion.

Only me?

**Comment by Yunkah99** [comment]
Same for me.

**Comment by marcofrias** [comment]
Same here

**Comment by bawaviki** [comment]
Some problem in building youtube-dl lazy extractor trying it to fix ASAP.

**Comment by marcofrias** [comment]
Working again, thanks Bawaviki

**Comment by MimuraKyosuke** [comment]
Thank you for fixing it!
