### ISSUE TITLE
Add code for sample app

### ISSUE THREAD

**Issue by JohannesPertl** [bawaviki/youtube-dl-android#4]
You show a gif of your sample app in your Readme, could you upload that code as well? Maybe in an extra repository, if you don't want to include it in this one, that would be very helpful :)

**Comment by bawaviki** [comment]
Sample app code was already added. Kindly fine it under app folder/directory. But I found that link is broken in Readme so I fix that link after reading this.

**Comment by JohannesPertl** [comment]
Oh I didn't see that, thanks!
