### ISSUE TITLE
Cannot download some videos

### ISSUE THREAD

**Issue by MimuraKyosuke** [bawaviki/youtube-dl-android#5]
Hello.

Cannot download this video.
https://www.youtube.com/watch?v=OUZTFpIqhVk&ab_channel=UruOfficialYouTubeChannel

But original youtube-dl can that.
Original youtube-dl was update in 2020.11.01.

Best regards.

**Comment by bawaviki** [comment]
As you known official repo of youtube-dl taken down so lazy youtube-dl use in app will not be update until I found any reliable solution.

**Comment by MimuraKyosuke** [comment]
Ok, thank you.

**Comment by bawaviki** [comment]
Try now, I somehow manage to update to youtube-dl latest version through unofficial repo.

**Comment by MimuraKyosuke** [comment]
I was able to download it!
Thank you for your kind support.

**Comment by MimuraKyosuke** [comment]
Hello.
I would like to confirm.
I think the official repo is back.
Is this app using the official repo now?

**Comment by bawaviki** [comment]
Thanks, reverted to old repo

**Comment by MimuraKyosuke** [comment]
Thank you!
