### ISSUE TITLE
java.io.IOException Permission Denied

### ISSUE THREAD

**Issue by codaman** [bawaviki/youtube-dl-android#9]
I always get permission denied error. I don't understand what did I do wrong 

String url = "www.youtube.com/watch?v=xxxxx";
        try {
            VideoInfo streamInfo = YoutubeDL.getInstance().getInfo(url);
            System.out.println();
        } catch (YoutubeDLException e) {
            e.printStackTrace();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

com.bawaviki.youtubedl_android.YoutubeDLException: java.io.IOException: Cannot run program "/data/user/0/xxxxxx/files/youtubedl-android/packages/usr/bin/python": error=13, Permission denied

**Comment by subhantariq33** [comment]
Have you found the solution ?

**Comment by codaman** [comment]
I could't found the solution yet. I don't understand that I is working on test application but I is not working in my project. I checked permissions

**Comment by subhantariq33** [comment]
Its working on buildToolsVersion 28
but not on buildToolsVersion 29 and buildToolsVersion 30

What kind of application are you developing?

**Comment by codaman** [comment]
Radio application but also users can search videos and listen it

**Comment by codaman** [comment]
yes it is fixed. thank you

**Comment by subhantariq33** [comment]
How do you fix it
